### ISSUE TITLE
bit of a newbie question.

### ISSUE THREAD

**Issue by hanetzer** [panda-re/panda#577]
Trying to basically follow along with the spotify drm pop article, for my
own case (drm'd ebooks should be illegal :grumble:). I created a vm
of win10pro, installed the target app (microsoft store app), had it pre
download the encrypted pdf. shut down the vm, called it again with
./bin/panda-system-x86_64 -enable-kvm -m 4096 win10.qcow2 -monitor stdio
(system is unusably slow without enable-kvm), issued the `begin_record app`
command, opened app, opened and decrypted ebook, closed app, 
stopped recording, shut down.

when I try to playback with callstack_instr and unigrams I get the following
output and nothing more:
```
./bin/panda-system-x86_64 -enable-kvm -m 4096 win10.qcow2 -replay app -panda 'callstack_instr;unigrams'
PANDA[core]:initializing callstack_instr
callstack_instr:  using asid stack_type
PANDA[core]:initializing unigrams
Initializing plugin unigrams
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:install/lib/panda/x86_64/panda_callstack_instr.so already loaded
loading snapshot
... done.
opening nondet log for read :	./app-rr-nondet.log
```

I've been letting the process sit for a while and nothing has changed. Is there
something I'm missing here fundamentally?

**Comment by AndrewFasano** [comment]
I see two unfortunate issue here- kvm and Windows 10.

PANDA's recording model is based on TCG and currently incompatible with kvm. See #177 for some more details.

Last time I checked, we've never been able to use a Windows 10 guest. Older versions of windows should be working fine.

Usually our workflow is to boot the guest (slowly) and then take a snapshot post-boot and use that as a starting point for everything.

**Comment by hanetzer** [comment]
See, primary issue is the login (win10 pin). kinda loops me back to the start
again each time I try to log in. So you're saying that rec and playback both
have to be done without kvm to work?

**Comment by AndrewFasano** [comment]
But you were able to get around the login issue? That's neat.

And yeah, unfortunately both have to be done without kvm since we don't have any instrumentation inside of the kvm code.

**Comment by hanetzer** [comment]
Nope, login issue still there. I'm trying to disable password/pin atm. I'll
report back when I have an answer. On another note, can you emulate
android in the arm emulator well enough? If that's more performant I may
tackle that route.

**Comment by AndrewFasano** [comment]
Unfortunately we [no longer support](https://github.com/panda-re/panda/blob/master/panda/docs/Android.md ) android - you could try using the [old version of panda](https://github.com/moyix/panda/) if you're desperate.

Can you get your target program to run under Windows 7? Then it should work

**Comment by hanetzer** [comment]
Maybe. On that note, how does one properly 'snapshot' the vm in
this case?

**Comment by AndrewFasano** [comment]
You can install/setup your guest with windows 7 using kvm, then take a snapshot using the qemu monitor (`savevm some_name`) then start panda again without kvm and use the monitor to restore the snapshot (`loadvm some_name`). Then you can start your recording via the monitor, make the system do something interesting, and then end your recording.

**Comment by hanetzer** [comment]
Ok, I have win10 booted and logged in, no kvm. 'savevm win10-booted' but
where is this 'stored' at?

**Comment by AndrewFasano** [comment]
Nice. That vm snapshot is the same as how qemu does it, it's actually saved inside the qcow file.

**Comment by hanetzer** [comment]
So wait. `./bin/panda-system-x86_64 win10.qcow -m 4096 -monitor stdio`, then when booted `savevm some-name`, then to reload, I do `./bin/panda-system-x86_64 win10.qcow -m 4096 -monitor stdio` and `loadvm some-name`?

**Comment by AndrewFasano** [comment]
Yep, or you could add `-loadvm some-name` to the command line. Either way, it should restore the snapshot for you.

**Comment by hanetzer** [comment]
gotcha. app crashed tho... dunno why specifically, no error message or
anything of that sort.

**Comment by hanetzer** [comment]
So about the win7 angle. Is that known to work better in this tooling?
The drm'ing bastards have an older win7/8 app, and I have a win7 lic
(downloading a fresh iso right now). x86/amd64 better for this sort of
thing?

**Comment by AndrewFasano** [comment]
Yeah, Windows 7 is known to work. 32 bit x86 is probably your best bet but amd64 should also work.

**Comment by hanetzer** [comment]
Now lets just hope the old version of their app for win7 can handle the ebook in
question. the crypto key is basically hard coded into a big-ass dll.

**Comment by AndrewFasano** [comment]
Good luck! Let us know how it goes

**Comment by hanetzer** [comment]
Beh. App says gpu/directx is too low to install on... may have to passthrough 
one of my spare gpus

**Comment by hanetzer** [comment]
@AndrewFasano got a thing going after much hemming and hawing:
```bash
./bin/panda-system-x86_64 -m 4096 -replay app -panda 'callstack_instr;unigrams'
PANDA[core]:initializing callstack_instr
callstack_instr:  using asid stack_type
PANDA[core]:initializing unigrams
Initializing plugin unigrams
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:/home/hanetzer/Projects/panda/panda-build/install/lib/panda/x86_64/panda_callstack_instr.so already loaded
loading snapshot
... done.
opening nondet log for read :	./app-rr-nondet.log
./app-rr-nondet.log:  26170620292 instrs total.
app:   261706203 (  1.00%) instrs.   52.54 sec.  2.88 GB ram.
app:   523412407 (  2.00%) instrs.   95.05 sec.  3.02 GB ram.
app:   785118610 (  3.00%) instrs.  152.66 sec.  3.44 GB ram.
app:  1046824814 (  4.00%) instrs.  232.04 sec.  3.75 GB ram.
app:  1308531017 (  5.00%) instrs.  323.64 sec.  4.13 GB ram.
app:  1570237220 (  6.00%) instrs.  404.69 sec.  4.26 GB ram.
app:  1831943421 (  7.00%) instrs.  501.87 sec.  4.37 GB ram.
app:  2093649626 (  8.00%) instrs.  594.68 sec.  4.44 GB ram.
```

Win7Ultx64 vm.

**Comment by AndrewFasano** [comment]
Glad to hear you got it working!

**Comment by janbbeck** [comment]
> Yeah, Windows 7 is known to work. 32 bit x86 is probably your best bet but amd64 should also work.

really? 64 bit windows is supported? I only see:
const char * valid_os_re[] = {
      "windows[-_]32[-_]xpsp[23]",
      "windows[-_]32[-_]7",
      "windows[-_]32[-_]2000",
      "linux[-_]32[-_].+",
      "linux[-_]64[-_].+",
      NULL
  };
